// AUTO-GENERATED by scripts/sync-postal-data.ts. Do not edit by hand.
// Source: https://chromium-i18n.appspot.com/ssl-aggregate-address/data/<CC>
// Snapshot date: 2026-07-17
// Data license: CC-BY 4.0 (see NOTICE)
//
// Upstream `zip_name_type`. Sparse by design: it is present only where the
// label differs from the default. Absent country => DEFAULT_POSTAL_LABEL.

export const DEFAULT_POSTAL_LABEL = "postal code";

export const POSTAL_LABELS: Record<string, string> = {
  AS: "zip",
  FM: "zip",
  GU: "zip",
  IE: "eircode",
  IN: "pin",
  MH: "zip",
  MP: "zip",
  PR: "zip",
  PW: "zip",
  UM: "zip",
  US: "zip",
  VI: "zip",
};
