name: Publish Package

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Debug - Environment Info
        run: |
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"
          echo "Current directory: $(pwd)"
          echo "Repository files:"
          ls -la

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm ci
          echo "Dependencies installed. Node modules:"
          ls -la node_modules

      - name: Run tests
        run: |
          echo "Running tests..."
          npm test
          echo "Tests completed."

      - name: Build
        run: |
          echo "Building project..."
          npm run build
          echo "Build completed. Dist folder contents:"
          ls -la dist

      - name: Bump version
        id: bump_version
        run: |
          OLD_VERSION=$(npm version --json | jq -r '.["postal-code-checker"]')
          echo "Old version: $OLD_VERSION"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          npm version patch -m "Bump version to %s"
          NEW_VERSION=$(npm version --json | jq -r '.["postal-code-checker"]')
          echo "New version: $NEW_VERSION"
          echo "old_version=$OLD_VERSION" >> $GITHUB_OUTPUT
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_WORKFLOW_TOKEN }}
          commit-message: "Bump version: ${{ steps.bump_version.outputs.old_version }} → ${{ steps.bump_version.outputs.new_version }}"
          title: "Bump version: ${{ steps.bump_version.outputs.old_version }} → ${{ steps.bump_version.outputs.new_version }}"
          body: "Automated version bump from ${{ steps.bump_version.outputs.old_version }} to ${{ steps.bump_version.outputs.new_version }}"
          branch: version-bump
          base: master

      - name: Publish to npm
        run: |
          echo "Publishing to npm..."
          npm publish --access public
          echo "Package published. Current npm info:"
          npm info postal-code-checker
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}

      - name: Debug - Final Check
        run: |
          echo "Workflow completed. Final repository state:"
          git status
          echo "Final package.json content:"
          cat package.json
